# Generated by Django 3.1.3 on 2021-06-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=20)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='blog_user_profile')),
            ],
            options={
                'db_table': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('blog_title', models.TextField(default='No Blog Title', max_length=200)),
                ('comment', models.TextField(max_length=500)),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.userdetails')),
            ],
            options={
                'db_table': 'All Comments',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blog_content', models.TextField(max_length=10200)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.userdetails')),
            ],
            options={
                'db_table': 'All Blogs',
            },
        ),
    ]
